vim.o.background = 'dark'
vim.o.termguicolors = true
vim.cmd.highlight 'clear'
if vim.fn.exists 'syntax_on' == 1 then
  vim.cmd.syntax 'reset'
end
vim.g.colors_name = 'kataware'

-- One restrained luminance ladder, with spectral accents reserved for meaning.
local p = {
  void = '#0B1020',
  night = '#10172A',
  surface = '#151F38',
  surface_high = '#1D2A49',
  border = '#2B3B62',
  muted = '#6B7FA2',
  dim = '#A8B7D0',
  fg = '#D9E2F2',
  starlight = '#EEF3FF',
  comet = '#60D7E8',
  blue = '#6CA8FF',
  violet = '#9B8CFF',
  pink = '#F08BC3',
  red = '#F2778B',
  gold = '#F2C38B',
  green = '#82D2B2',
}

local groups = {
  -- Editor surfaces
  Normal = { fg = p.fg, bg = p.void },
  NormalNC = { fg = p.dim, bg = p.void },
  NormalFloat = { fg = p.fg, bg = p.surface },
  FloatBorder = { fg = p.border, bg = p.surface },
  FloatTitle = { fg = p.comet, bg = p.surface, bold = true },
  ColorColumn = { bg = p.night },
  Cursor = { fg = p.void, bg = p.starlight },
  CursorColumn = { bg = p.night },
  CursorLine = { bg = p.night },
  CursorLineNr = { fg = p.gold, bg = p.night, bold = true },
  LineNr = { fg = p.border },
  SignColumn = { fg = p.muted, bg = p.void },
  FoldColumn = { fg = p.muted, bg = p.void },
  Folded = { fg = p.dim, bg = p.night },
  WinSeparator = { fg = p.border },
  VertSplit = { fg = p.border },
  Visual = { bg = p.surface_high },
  VisualNOS = { bg = p.surface_high },
  Search = { fg = p.void, bg = p.gold },
  IncSearch = { fg = p.void, bg = p.pink, bold = true },
  CurSearch = { fg = p.void, bg = p.comet, bold = true },
  MatchParen = { fg = p.starlight, bg = p.border, bold = true },
  Substitute = { fg = p.void, bg = p.red },
  NonText = { fg = p.border },
  Whitespace = { fg = p.border },
  EndOfBuffer = { fg = p.void },
  SpecialKey = { fg = p.border },
  Directory = { fg = p.comet },
  Title = { fg = p.violet, bold = true },
  Conceal = { fg = p.muted },
  Question = { fg = p.comet },
  MoreMsg = { fg = p.green },
  ModeMsg = { fg = p.gold, bold = true },
  WarningMsg = { fg = p.gold },
  ErrorMsg = { fg = p.red, bold = true },

  -- Chrome
  StatusLine = { fg = p.fg, bg = p.surface },
  StatusLineNC = { fg = p.muted, bg = p.night },
  TabLine = { fg = p.muted, bg = p.night },
  TabLineFill = { bg = p.void },
  TabLineSel = { fg = p.void, bg = p.comet, bold = true },
  WinBar = { fg = p.dim, bg = p.void },
  WinBarNC = { fg = p.muted, bg = p.void },
  Pmenu = { fg = p.dim, bg = p.surface },
  PmenuSel = { fg = p.starlight, bg = p.surface_high, bold = true },
  PmenuSbar = { bg = p.night },
  PmenuThumb = { bg = p.border },
  PmenuMatch = { fg = p.comet, bold = true },
  PmenuMatchSel = { fg = p.comet, bg = p.surface_high, bold = true },
  QuickFixLine = { fg = p.starlight, bg = p.surface_high, bold = true },
  WildMenu = { fg = p.void, bg = p.comet },

  -- Core syntax
  Comment = { fg = p.muted, italic = true },
  Constant = { fg = p.gold },
  String = { fg = p.green },
  Character = { fg = p.green },
  Number = { fg = p.gold },
  Boolean = { fg = p.gold, bold = true },
  Float = { fg = p.gold },
  Identifier = { fg = p.fg },
  Function = { fg = p.blue },
  Statement = { fg = p.violet },
  Conditional = { fg = p.violet },
  Repeat = { fg = p.violet },
  Label = { fg = p.pink },
  Operator = { fg = p.comet },
  Keyword = { fg = p.violet },
  Exception = { fg = p.pink },
  PreProc = { fg = p.pink },
  Include = { fg = p.violet },
  Define = { fg = p.pink },
  Macro = { fg = p.pink },
  PreCondit = { fg = p.pink },
  Type = { fg = p.comet },
  StorageClass = { fg = p.violet },
  Structure = { fg = p.comet },
  Typedef = { fg = p.comet },
  Special = { fg = p.pink },
  SpecialChar = { fg = p.gold },
  Tag = { fg = p.blue },
  Delimiter = { fg = p.dim },
  SpecialComment = { fg = p.muted, italic = true },
  Debug = { fg = p.red },
  Underlined = { fg = p.blue, underline = true },
  Ignore = { fg = p.muted },
  Error = { fg = p.red },
  Todo = { fg = p.void, bg = p.gold, bold = true },

  -- Diffs and version control
  DiffAdd = { fg = p.green, bg = '#142C31' },
  DiffChange = { fg = p.blue, bg = '#182846' },
  DiffDelete = { fg = p.red, bg = '#2D192A' },
  DiffText = { fg = p.starlight, bg = '#253A68', bold = true },
  Added = { fg = p.green },
  Changed = { fg = p.blue },
  Removed = { fg = p.red },
  GitSignsAdd = { fg = p.green },
  GitSignsChange = { fg = p.blue },
  GitSignsDelete = { fg = p.red },

  -- Diagnostics
  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.gold },
  DiagnosticInfo = { fg = p.blue },
  DiagnosticHint = { fg = p.comet },
  DiagnosticOk = { fg = p.green },
  DiagnosticVirtualTextError = { fg = p.red, bg = '#241625' },
  DiagnosticVirtualTextWarn = { fg = p.gold, bg = '#28243A' },
  DiagnosticVirtualTextInfo = { fg = p.blue, bg = '#172442' },
  DiagnosticVirtualTextHint = { fg = p.comet, bg = '#14283A' },
  DiagnosticUnderlineError = { sp = p.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = p.gold, undercurl = true },
  DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = p.comet, undercurl = true },
  LspReferenceText = { bg = p.surface_high },
  LspReferenceRead = { bg = p.surface_high },
  LspReferenceWrite = { bg = p.surface_high, underline = true },
  LspInlayHint = { fg = p.dim, bg = p.night },
  LspCodeLens = { fg = p.muted },
  LspSignatureActiveParameter = { fg = p.comet, bold = true },

  -- Completion and pickers
  ComplHint = { fg = p.dim, italic = true },
  ComplHintMore = { fg = p.comet, bold = true },
  BlinkCmpMenu = { fg = p.dim, bg = p.surface },
  BlinkCmpMenuBorder = { fg = p.border, bg = p.surface },
  BlinkCmpMenuSelection = { fg = p.starlight, bg = p.surface_high, bold = true },
  BlinkCmpLabel = { fg = p.dim },
  BlinkCmpLabelMatch = { fg = p.comet, bold = true },
  BlinkCmpLabelDeprecated = { fg = p.muted, strikethrough = true },
  BlinkCmpKind = { fg = p.violet },
  BlinkCmpSource = { fg = p.muted, italic = true },
  BlinkCmpDoc = { fg = p.dim, bg = p.surface },
  BlinkCmpDocBorder = { fg = p.border, bg = p.surface },
  TelescopeNormal = { fg = p.dim, bg = p.surface },
  TelescopeBorder = { fg = p.border, bg = p.surface },
  TelescopePromptNormal = { fg = p.fg, bg = p.surface_high },
  TelescopePromptBorder = { fg = p.violet, bg = p.surface_high },
  TelescopePromptTitle = { fg = p.void, bg = p.violet, bold = true },
  TelescopePreviewTitle = { fg = p.void, bg = p.blue, bold = true },
  TelescopeResultsTitle = { fg = p.void, bg = p.comet, bold = true },
  TelescopeSelection = { fg = p.starlight, bg = p.surface_high },
  TelescopeMatching = { fg = p.comet, bold = true },
  SnacksPickerMatch = { fg = p.comet, bold = true },
  SnacksPickerBorder = { fg = p.border },
  SnacksPickerTitle = { fg = p.violet, bold = true },
  SnacksDashboardHeader = { fg = p.violet },
  SnacksDashboardKey = { fg = p.comet, bold = true },
  SnacksDashboardDesc = { fg = p.dim },
  SnacksDashboardIcon = { fg = p.blue },
  SnacksDashboardFooter = { fg = p.muted, italic = true },
  SnacksIndent = { fg = p.border },
  SnacksIndentScope = { fg = p.violet },

  -- Common plugin chrome
  WhichKey = { fg = p.comet },
  WhichKeyGroup = { fg = p.violet },
  WhichKeyDesc = { fg = p.dim },
  WhichKeySeparator = { fg = p.border },
  WhichKeyBorder = { fg = p.border, bg = p.surface },
  LazyButton = { fg = p.dim, bg = p.surface_high },
  LazyButtonActive = { fg = p.void, bg = p.comet, bold = true },
  LazyH1 = { fg = p.void, bg = p.violet, bold = true },
  OilDir = { fg = p.comet },
  OilDirIcon = { fg = p.blue },
  OilLink = { fg = p.violet },
  TodoFgTODO = { fg = p.blue },
  TodoFgNOTE = { fg = p.comet },
  TodoFgWARN = { fg = p.gold },
  TodoFgFIX = { fg = p.red },

  -- mini.nvim statusline
  MiniStatuslineModeNormal = { fg = p.void, bg = p.blue, bold = true },
  MiniStatuslineModeInsert = { fg = p.void, bg = p.green, bold = true },
  MiniStatuslineModeVisual = { fg = p.void, bg = p.violet, bold = true },
  MiniStatuslineModeReplace = { fg = p.void, bg = p.pink, bold = true },
  MiniStatuslineModeCommand = { fg = p.void, bg = p.gold, bold = true },
  MiniStatuslineModeOther = { fg = p.void, bg = p.comet, bold = true },
  MiniStatuslineDevinfo = { fg = p.dim, bg = p.surface_high },
  MiniStatuslineFilename = { fg = p.fg, bg = p.surface },
  MiniStatuslineFileinfo = { fg = p.dim, bg = p.surface_high },
  MiniStatuslineInactive = { fg = p.muted, bg = p.night },
  MiniTablineCurrent = { fg = p.void, bg = p.comet, bold = true },
  MiniTablineVisible = { fg = p.dim, bg = p.surface },
  MiniTablineHidden = { fg = p.muted, bg = p.night },
  MiniTablineModifiedCurrent = { fg = p.red, bg = p.comet, bold = true },
  MiniTablineModifiedVisible = { fg = p.gold, bg = p.surface },
  MiniTablineModifiedHidden = { fg = p.gold, bg = p.night },
  MiniTablineFill = { bg = p.void },
}

for group, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, group, spec)
end

local links = {
  ['@comment'] = 'Comment',
  ['@comment.documentation'] = 'SpecialComment',
  ['@constant'] = 'Constant',
  ['@constant.builtin'] = 'Special',
  ['@string'] = 'String',
  ['@string.escape'] = 'SpecialChar',
  ['@character'] = 'Character',
  ['@number'] = 'Number',
  ['@boolean'] = 'Boolean',
  ['@function'] = 'Function',
  ['@function.builtin'] = 'Special',
  ['@function.call'] = 'Function',
  ['@function.method'] = 'Function',
  ['@constructor'] = 'Type',
  ['@keyword'] = 'Keyword',
  ['@keyword.function'] = 'Keyword',
  ['@keyword.return'] = 'Keyword',
  ['@keyword.import'] = 'Include',
  ['@conditional'] = 'Conditional',
  ['@repeat'] = 'Repeat',
  ['@operator'] = 'Operator',
  ['@type'] = 'Type',
  ['@type.builtin'] = 'Type',
  ['@variable'] = 'Identifier',
  ['@variable.builtin'] = 'Special',
  ['@variable.member'] = 'Identifier',
  ['@property'] = 'Identifier',
  ['@attribute'] = 'PreProc',
  ['@tag'] = 'Tag',
  ['@tag.attribute'] = 'Identifier',
  ['@tag.delimiter'] = 'Delimiter',
  ['@punctuation.bracket'] = 'Delimiter',
  ['@punctuation.delimiter'] = 'Delimiter',
  ['@markup.heading'] = 'Title',
  ['@markup.strong'] = 'Bold',
  ['@markup.italic'] = 'Italic',
  ['@markup.link'] = 'Underlined',
  ['@markup.raw'] = 'String',
  ['@diff.plus'] = 'Added',
  ['@diff.minus'] = 'Removed',
  ['@diff.delta'] = 'Changed',
  ['@lsp.type.class'] = 'Type',
  ['@lsp.type.decorator'] = 'PreProc',
  ['@lsp.type.enum'] = 'Type',
  ['@lsp.type.enumMember'] = 'Constant',
  ['@lsp.type.function'] = 'Function',
  ['@lsp.type.interface'] = 'Type',
  ['@lsp.type.macro'] = 'Macro',
  ['@lsp.type.method'] = 'Function',
  ['@lsp.type.namespace'] = 'Include',
  ['@lsp.type.parameter'] = 'Identifier',
  ['@lsp.type.property'] = 'Identifier',
  ['@lsp.type.struct'] = 'Type',
  ['@lsp.type.type'] = 'Type',
  ['@lsp.type.typeParameter'] = 'Type',
  ['@lsp.type.variable'] = 'Identifier',
}

for group, target in pairs(links) do
  vim.api.nvim_set_hl(0, group, { link = target })
end

vim.api.nvim_set_hl(0, 'Bold', { bold = true })
vim.api.nvim_set_hl(0, 'Italic', { italic = true })

local terminal = {
  p.void,
  p.red,
  p.green,
  p.gold,
  p.blue,
  p.violet,
  p.comet,
  p.dim,
  p.muted,
  '#FF91A4',
  '#A0E0C2',
  '#FFD49F',
  '#91BAFF',
  '#B9ACFF',
  '#86E9F2',
  p.starlight,
}
for index, color in ipairs(terminal) do
  vim.g['terminal_color_' .. (index - 1)] = color
end
