local function imap(lhs, rhs)
  vim.keymap.set('i', lhs, rhs, { buffer = true })
end

imap(',f', '<Esc>/<++><CR>:nohlsearch<CR>"_c4l')
imap('<C-e>', '<Esc>/<++><CR>:nohlsearch<CR>"_c4l')
imap(',w', '<Esc>/ <++><CR>:nohlsearch<CR>"_c5l<CR>')
imap(',n', '---<CR><CR>')
imap(',b', '**** <++><Esc>F*hi')
imap(',s', '~~~~ <++><Esc>F~hi')
imap(',i', '** <++><Esc>F*i')
imap(',d', '`` <++><Esc>F`i')
imap(',c', '```<CR><++><CR>```<CR><CR><++><Esc>4kA')
imap(',m', '- [ ] ')
imap(',p', '![](<++>) <++><Esc>F[a')
imap(',a', '[](<++>) <++><Esc>F[a')
imap(',1', '# <CR><++><Esc>kA')
imap(',2', '## <CR><++><Esc>kA')
imap(',3', '### <CR><++><Esc>kA')
imap(',4', '#### <CR><++><Esc>kA')
imap(',l', '--------<CR>')
imap(',h', '<font color=><++></font> <++><Esc>F=a')
imap(',u', '`` <++><Esc>F`i')
