local ls = require 'luasnip'
local s = ls.snippet
local i = ls.insert_node
local t = ls.text_node
local f = ls.function_node

local function makefile_snippet(name, compiler, ext)
  return s(name, {
    t { '# Makefile generated by luasnip', '' },
    t 'CC      = ',
    i(1, compiler),
    t { '', 'CFLAGS  = -Wall -Wextra ' },
    i(2, ''),
    t { '', 'LDFLAGS = ' },
    i(3, ''),
    t { '', '', 'TARGET  = ' },
    i(4, 'main'),
    t { '', 'SRCS    = ' },
    i(5, 'main.' .. ext),
    t { '', 'OBJS    = $(SRCS:.' .. ext .. '=.o)', '' },

    t { '', '.PHONY: all clean', '' },
    t { '', 'all: $(TARGET)', '' },

    t { '', '$(TARGET): $(OBJS)', '' },
    t '\t$(CC) $(OBJS) -o $@ $(LDFLAGS)', -- 链接阶段：使用 LDFLAGS

    t { '', '', '%.o: %.' .. ext, '' },
    t '\t$(CC) $(CFLAGS) -c $< -o $@', -- 编译阶段：使用 CFLAGS

    t { '', '', 'clean:', '' },
    t { '\trm -f $(OBJS) $(TARGET)', '' },
  })
end

ls.add_snippets('make', {
  makefile_snippet('makefile_c', 'gcc', 'c'),
  makefile_snippet('makefile_cpp', 'g++', 'cpp'),
})
