local ls = require 'luasnip'
local s = ls.snippet
local i = ls.insert_node
local t = ls.text_node

local function makefile_snippet(name, compiler, ext)
  return s(name, {
    t { '# Makefile generated by luasnip', '' },
    t { 'CC = ' },
    i(1, compiler),
    t { '', 'CFLAGS = -Wall -Werror' },
    t { '', 'TARGET = ' },
    i(2, 'my_program'),
    t { '', 'SRCS = ' },
    i(3, 'main.' .. ext),
    t { '', 'OBJS = $(SRCS:.' .. ext .. '=.o)', '' },
    t { 'all: $(TARGET)', '' },
    t { '\t$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)', '' },
    t { '', '$(TARGET): $(OBJS)', '' },
    t { '\t$(CC) $(CFLAGS) -o $@ $^', '' },
    t { '', '%.o: %.' .. ext, '' },
    t { '\t$(CC) $(CFLAGS) -c $< -o $@', '' },
    t { '', 'clean:', '' },
    t { '\trm -f $(OBJS) $(TARGET)', '' },
  })
end

ls.add_snippets('make', {
  makefile_snippet('makefile_c', 'gcc', 'c'),
  makefile_snippet('makefile_cpp', 'g++', 'cpp'),
})
